title: Melisa Savich
url: "https://mksavic.github.io/"
baseurl: ""

markdown: kramdown
favicon: yes
#ins_logo: "./bits-logo.png"

tracking_id: "UA-139062934-1"

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "cv.pdf"
 - name: "CV of Failures"
   link: "failures"
 - name: "Contact"
   link: "contact"
